export const TOUS_METIERS = [
  "Maçon","Coffreur-bancheur","Terrassier","Démolisseur","Charpentier bois",
  "Charpentier métallique","Couvreur","Étancheur","Bardeur","Façadier","Enduiseur","Ferrailleur",
  "Plombier","Plombier-chauffagiste","Chauffagiste","Électricien","Électricien industriel",
  "Peintre","Peintre-décorateur","Carreleur","Parqueteur","Menuisier","Menuisier-ébéniste",
  "Serrurier","Métallier","Plaquiste","Plâtrier","Jointeur","Isolation thermique","Isolation phonique",
  "Installateur panneaux solaires","Installateur pompe à chaleur","Poêliste","Ramoneur",
  "Installateur VMC","Climaticien","Frigoriste","Domoticien","Électricien photovoltaïque","Géothermiste",
  "Cuisiniste","Agenceur","Tapissier-décorateur","Miroitier","Vitrier","Paveur","Dalleur",
  "Pisciniste","Paysagiste","Clôturiste","Portailiste","Terrassier VRD",
  "Diagnostiqueur immobilier","Géomètre-expert","Architecte","Maître d'œuvre",
  "Économiste de la construction","Bureau de contrôle","Coordonnateur SPS","Ingénieur structure","Thermicien",
  "Ravaleur de façades","Nettoyeur industriel","Désamianteur","Plombier urgence",
  "Électricien urgence","Serrurier urgence","Déboucheur","Désinfecteur","Dératiseur",
];

export const DEPARTEMENTS = {
  "01":"Ain","02":"Aisne","03":"Allier","04":"Alpes-de-Haute-Provence","05":"Hautes-Alpes",
  "06":"Alpes-Maritimes","07":"Ardèche","08":"Ardennes","09":"Ariège","10":"Aube",
  "11":"Aude","12":"Aveyron","13":"Bouches-du-Rhône","14":"Calvados","15":"Cantal",
  "16":"Charente","17":"Charente-Maritime","18":"Cher","19":"Corrèze","21":"Côte-d'Or",
  "22":"Côtes-d'Armor","23":"Creuse","24":"Dordogne","25":"Doubs","26":"Drôme",
  "27":"Eure","28":"Eure-et-Loir","29":"Finistère","2A":"Corse-du-Sud","2B":"Haute-Corse",
  "30":"Gard","31":"Haute-Garonne","32":"Gers","33":"Gironde","34":"Hérault",
  "35":"Ille-et-Vilaine","36":"Indre","37":"Indre-et-Loire","38":"Isère","39":"Jura",
  "40":"Landes","41":"Loir-et-Cher","42":"Loire","43":"Haute-Loire","44":"Loire-Atlantique",
  "45":"Loiret","46":"Lot","47":"Lot-et-Garonne","48":"Lozère","49":"Maine-et-Loire",
  "50":"Manche","51":"Marne","52":"Haute-Marne","53":"Mayenne","54":"Meurthe-et-Moselle",
  "55":"Meuse","56":"Morbihan","57":"Moselle","58":"Nièvre","59":"Nord",
  "60":"Oise","61":"Orne","62":"Pas-de-Calais","63":"Puy-de-Dôme","64":"Pyrénées-Atlantiques",
  "65":"Hautes-Pyrénées","66":"Pyrénées-Orientales","67":"Bas-Rhin","68":"Haut-Rhin","69":"Rhône",
  "70":"Haute-Saône","71":"Saône-et-Loire","72":"Sarthe","73":"Savoie","74":"Haute-Savoie",
  "75":"Paris","76":"Seine-Maritime","77":"Seine-et-Marne","78":"Yvelines","79":"Deux-Sèvres",
  "80":"Somme","81":"Tarn","82":"Tarn-et-Garonne","83":"Var","84":"Vaucluse",
  "85":"Vendée","86":"Vienne","87":"Haute-Vienne","88":"Vosges","89":"Yonne",
  "90":"Territoire de Belfort","91":"Essonne","92":"Hauts-de-Seine","93":"Seine-Saint-Denis",
  "94":"Val-de-Marne","95":"Val-d'Oise","971":"Guadeloupe","972":"Martinique",
  "973":"Guyane","974":"La Réunion","976":"Mayotte",
};

export const ARTISANS = [
  { id:1, nom:"Jean-Marc Rousseau", metier:"Plombier", ville:"Paris", cp:"75011", note:4.9, avis:128, exp:12, dispo:"Dès demain", tags:["Installation","Dépannage","Chauffage"], prix:45, certifie:true, rge:true, img:"https://i.pravatar.cc/150?u=1", tel:"06 12 34 56 78", desc:"Plombier certifié RGE avec 12 ans d'expérience. Intervient sur Paris et sa banlieue.", assurance:"Décennale + RC Pro", langues:["Français","Anglais"] },
  { id:2, nom:"Sophie Lefèvre", metier:"Électricienne", ville:"Lyon", cp:"69003", note:4.8, avis:94, exp:8, dispo:"Cette semaine", tags:["Tableau électrique","Domotique","Rénovation"], prix:50, certifie:true, rge:true, img:"https://i.pravatar.cc/150?u=2", tel:"06 98 76 54 32", desc:"Spécialisée en rénovation électrique et installation domotique.", assurance:"Décennale", langues:["Français"] },
  { id:3, nom:"Mohamed Benali", metier:"Peintre", ville:"Marseille", cp:"13008", note:4.7, avis:67, exp:15, dispo:"Dès que possible", tags:["Intérieur","Extérieur","Ravalement"], prix:35, certifie:false, rge:false, img:"https://i.pravatar.cc/150?u=3", tel:"06 11 22 33 44", desc:"Peintre décorateur avec 15 ans d'expérience.", assurance:"RC Pro", langues:["Français","Arabe"] },
  { id:4, nom:"Claire Dubois", metier:"Maçon", ville:"Paris", cp:"75014", note:4.6, avis:41, exp:20, dispo:"Dans 2 semaines", tags:["Gros œuvre","Extension","Rénovation"], prix:55, certifie:true, rge:false, img:"https://i.pravatar.cc/150?u=4", tel:"06 55 44 33 22", desc:"Maçon généraliste, spécialiste des extensions et surélévations.", assurance:"Décennale + RC Pro", langues:["Français"] },
  { id:5, nom:"Lucas Martin", metier:"Plombier", ville:"Lyon", cp:"69007", note:4.5, avis:33, exp:5, dispo:"Dès demain", tags:["Dépannage","Fuite","Sanitaire"], prix:40, certifie:true, rge:true, img:"https://i.pravatar.cc/150?u=5", tel:"06 77 88 99 00", desc:"Jeune plombier dynamique, réactif pour les urgences.", assurance:"RC Pro", langues:["Français","Espagnol"] },
  { id:6, nom:"Isabelle Moreau", metier:"Électricienne", ville:"Paris", cp:"75017", note:4.9, avis:156, exp:18, dispo:"Dès que possible", tags:["Mise aux normes","VMC","Éclairage"], prix:52, certifie:true, rge:true, img:"https://i.pravatar.cc/150?u=6", tel:"06 13 24 35 46", desc:"Experte en mise aux normes NF C 15-100.", assurance:"Décennale", langues:["Français"] },
  { id:7, nom:"Thomas Girard", metier:"Couvreur", ville:"Bordeaux", cp:"33000", note:4.8, avis:89, exp:14, dispo:"Cette semaine", tags:["Tuiles","Ardoise","Zinc"], prix:48, certifie:true, rge:false, img:"https://i.pravatar.cc/150?u=7", tel:"06 22 33 44 55", desc:"Couvreur spécialisé toutes couvertures, réparations et rénovations.", assurance:"Décennale + RC Pro", langues:["Français"] },
  { id:8, nom:"Amina Traore", metier:"Carreleur", ville:"Toulouse", cp:"31000", note:4.7, avis:52, exp:9, dispo:"Dès demain", tags:["Salle de bain","Cuisine","Grand format"], prix:38, certifie:true, rge:false, img:"https://i.pravatar.cc/150?u=8", tel:"06 44 55 66 77", desc:"Carreleur spécialiste grands formats et salles de bain.", assurance:"RC Pro", langues:["Français"] },
  { id:9, nom:"Pierre Dumont", metier:"Installateur panneaux solaires", ville:"Nice", cp:"06000", note:4.9, avis:203, exp:10, dispo:"Dès que possible", tags:["Photovoltaïque","Thermique","Autoconsommation"], prix:60, certifie:true, rge:true, img:"https://i.pravatar.cc/150?u=9", tel:"06 55 66 77 88", desc:"Expert certifié QualiPV pour l'installation de panneaux solaires.", assurance:"Décennale", langues:["Français","Italien"] },
  { id:10, nom:"Nathalie Bernard", metier:"Architecte", ville:"Paris", cp:"75008", note:5.0, avis:47, exp:22, dispo:"Dans 1 semaine", tags:["Rénovation","Extension","Permis de construire"], prix:90, certifie:true, rge:false, img:"https://i.pravatar.cc/150?u=10", tel:"06 88 99 00 11", desc:"Architecte DPLG spécialisée en rénovation de l'habitat.", assurance:"RC Pro", langues:["Français","Anglais","Espagnol"] },
  { id:11, nom:"Karim Aziz", metier:"Plaquiste", ville:"Lille", cp:"59000", note:4.6, avis:38, exp:7, dispo:"Dès que possible", tags:["Cloisons","Faux plafond","Isolation"], prix:36, certifie:true, rge:false, img:"https://i.pravatar.cc/150?u=11", tel:"06 11 99 88 77", desc:"Plaquiste spécialisé en cloisons sèches et faux plafonds.", assurance:"RC Pro", langues:["Français","Arabe"] },
  { id:12, nom:"Élodie Petit", metier:"Paysagiste", ville:"Bordeaux", cp:"33200", note:4.8, avis:71, exp:11, dispo:"Cette semaine", tags:["Jardin","Terrasse","Piscine"], prix:42, certifie:true, rge:false, img:"https://i.pravatar.cc/150?u=12", tel:"06 00 11 22 33", desc:"Paysagiste créatrice, spécialiste des jardins méditerranéens.", assurance:"RC Pro", langues:["Français","Anglais"] },
];

export const VILLES_LOCALES = [
  "Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Montpellier","Strasbourg","Bordeaux","Lille",
  "Rennes","Reims","Le Havre","Saint-Étienne","Toulon","Grenoble","Dijon","Angers","Nîmes",
  "Le Mans","Aix-en-Provence","Clermont-Ferrand","Brest","Tours","Amiens","Limoges","Annecy",
  "Perpignan","Metz","Besançon","Orléans","Rouen","Mulhouse","Caen","Nancy","Avignon",
  "Poitiers","Versailles","Pau","Antibes","Cannes","Calais","Béziers","Bourges",
  "La Rochelle","Quimper","Troyes","Ajaccio","Valenciennes","Chambéry","Niort","Montauban",
  "Bayonne","Meaux","Évreux","Belfort","Beauvais","Laval","Chartres","Aubagne","Auxerre",
  "Albi","Arles","Maubeuge","Creil","Colmar","Nanterre","Villejuif","Sevran","Bondy",
];